### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by ash11sh** [Qengineering/TensorFlow_Lite_RPi_32-bits#1]
`line 117 error: no matching function for call to ‘get_top_n<uint8_t>(unsigned char*, int&, int, const float&, std::vector<std::pair<float, int> >*, bool)’|`

**Comment by Qengineering** [comment]
Two problems.
1) Your error was caused by type casting a TfLiteType to a boolean. Fix it in the code. 
2) As of  version 2.3.0, TensorFlow Lite uses dlopen() and dlclose(). These are in libdl.so.2. Add it to the linker with the -ldl flag

Please reload the example.
